import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "افتح ياسمسم",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-white flex flex-col gap-[100px]">
        {children}
      </body>
    </html>
  );
}
